"""add weather readings

Revision ID: 321c5b988b7c
Revises: 3f1c4bf9f174
Create Date: 2026-10-06 16:18:37.077095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321c5b988b7c'
down_revision: Union[str, None] = '3f1c4bf9f174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
