"""add attraction image table

Revision ID: 3f1c4bf9f174
Revises: 4cd4e4d3535e
Create Date: 2026-09-19 16:50:07.605922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1c4bf9f174'
down_revision: Union[str, None] = '4cd4e4d3535e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attraction_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attraction_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('external_image_id', sa.String(length=500), nullable=True),
    sa.Column('bucket_name', sa.String(length=100), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('attribution', sa.JSON(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attraction_id'], ['attractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_name', 'storage_key', name='uix_attraction_image_storage')
    )
    op.create_index('ix_attraction_images_attraction_active', 'attraction_images', ['attraction_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_attraction_images_attraction_id'), 'attraction_images', ['attraction_id'], unique=False)
    op.create_index('ix_attraction_images_attraction_primary', 'attraction_images', ['attraction_id', 'is_primary'], unique=False)
    op.create_index(op.f('ix_attraction_images_content_hash'), 'attraction_images', ['content_hash'], unique=False)
    op.create_index(op.f('ix_attraction_images_external_image_id'), 'attraction_images', ['external_image_id'], unique=False)
    op.create_index(op.f('ix_attraction_images_is_active'), 'attraction_images', ['is_active'], unique=False)
    op.create_index(op.f('ix_attraction_images_source_id'), 'attraction_images', ['source_id'], unique=False)
    op.create_index(op.f('ix_attraction_images_source_type'), 'attraction_images', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attraction_images_source_type'), table_name='attraction_images')
    op.drop_index(op.f('ix_attraction_images_source_id'), table_name='attraction_images')
    op.drop_index(op.f('ix_attraction_images_is_active'), table_name='attraction_images')
    op.drop_index(op.f('ix_attraction_images_external_image_id'), table_name='attraction_images')
    op.drop_index(op.f('ix_attraction_images_content_hash'), table_name='attraction_images')
    op.drop_index('ix_attraction_images_attraction_primary', table_name='attraction_images')
    op.drop_index(op.f('ix_attraction_images_attraction_id'), table_name='attraction_images')
    op.drop_index('ix_attraction_images_attraction_active', table_name='attraction_images')
    op.drop_table('attraction_images')
    # ### end Alembic commands ###
