"""add modified wheather

Revision ID: 8295ce04d40b
Revises: d9e7f6a5b4c3
Create Date: 2026-10-08 04:42:13.780528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8295ce04d40b'
down_revision: Union[str, None] = 'd9e7f6a5b4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_weather_readings_station_id'), 'weather_readings', ['station_id'], unique=False)
    op.drop_constraint(op.f('uq_weather_stations_station_id'), 'weather_stations', type_='unique')
    op.create_index(op.f('ix_weather_stations_station_id'), 'weather_stations', ['station_id'], unique=True)
    op.create_index(op.f('ix_weather_stations_station_name'), 'weather_stations', ['station_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_stations_station_name'), table_name='weather_stations')
    op.drop_index(op.f('ix_weather_stations_station_id'), table_name='weather_stations')
    op.create_unique_constraint(op.f('uq_weather_stations_station_id'), 'weather_stations', ['station_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_weather_readings_station_id'), table_name='weather_readings')
    # ### end Alembic commands ###
